Repository TechSpiritSS/Terminal-Portfolio, pull requests merged in 2022-10, with the labels that each got.

#3 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: good first issue, hacktoberfest

#5 adds approved favicon to the website
  favicon.ico
  index.html
Labels: good first issue, hacktoberfest

#7 Added exit functionality & corrected a small spelling mistake
  script.js
Labels: good first issue, hacktoberfest

#13 Solved merge conflict & replaced if-else with switch case
  script.js
Labels: good first issue, hacktoberfest

#17 resolved footer_removed issue on clear command
  index.html
  style.css
Labels: good first issue, hactoberfest-accepted

#18 feat: add windows maximize feature
  index.html
  script.js
  style.css
Labels: hactoberfest-accepted

#24 Added arrow keys functionality
  script.js
Labels: hactoberfest-accepted

#27 Added Cheer command
  script.js
  style.css
Labels: hactoberfest-accepted

#26 feat: add green/yellow window click event
  index.html
  script.js
  style.css
Labels: hactoberfest-accepted

#31 Added Cheer Command
  script.js
  style.css
Labels: hactoberfest-accepted

#32 Added PR template
  .github/pull_request_template.md
Labels: documentation, hactoberfest-accepted

#41 Added contributing file
  CONTRIBUTING.md
Labels: documentation, good first issue, hactoberfest-accepted

#47 Added tab autocomplete feature
  script.js
Labels: hactoberfest-accepted

#48 Add 'blogs' command to fetch latest blogs
  script.js
Labels: hactoberfest-accepted

#52 Added command "contributors"
  script.js
Labels: hactoberfest-accepted

#67 new command "ipconfig"
  script.js
Labels: hactoberfest-accepted

#59 Added open graph meta tags
  index.html
Labels: hactoberfest-accepted
